---
title: "Laugenknoten Index"
author: "rgratz"
date: '2020-02-10'
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  warning = FALSE,
  message = FALSE
)

library(tidyverse)
library(ggplot2)
```

```{r, include=FALSE}
# laugenknoten_data <- read_csv("Laugendata.csv")
laugenknoten_data <- read_csv(url("https://raw.githubusercontent.com/GratzR/laugen_index/master/Laugendata.csv"))

laugenknoten_data <- laugenknoten_data %>% 
  mutate(
    ID = row_number(),
    Weekday = lubridate::wday(laugenknoten_data$Date, label=T),
    Time = as.POSIXct(Time),
    Timeframe = case_when(
      lubridate::hour(Time) >= 14  ~ "14:00 - Ende",
      lubridate::hour(Time) >= 12  ~ "12:00 - 14:00",
      lubridate::hour(Time) >= 10  ~ "10:00 - 12:00",
      lubridate::hour(Time) <= 9  ~ "< 10:00"
    )
  ) %>% 
  select(ID,Date,Weekday,Time,Timeframe,Amount,Mensa)
laugenknoten_data
```

```{r, include=FALSE}
laugenknoten_data <- laugenknoten_data %>% 
  group_by(
    Mensa,
    Weekday,
    Timeframe
  ) %>% 
  summarise(
    average = mean(Amount)
  ) %>% 
  arrange(Timeframe)

laugenknoten_data
```

```{r, echo=FALSE}
laugenknoten_data %>% 
  ggplot(
    aes(
      x = Weekday,
      y = average
    )
  ) +
  geom_col() + 
  labs(
    title = "Laugenknoten nach Wochentagen",
    x = "Wochentag",
    y = "Durchschnitt"
  ) + 
  facet_grid(Mensa ~ Timeframe)
```


